default: &default
  :linkedin_api_key: g15uvnfqkz3s
  :linkein_secret_key: Ha01Zfo9hDJRDusV
  :linkedin_client_options:
    :request_token_path: '/uas/oauth/requestToken?scope=r_basicprofile+rw_nus'
    :access_token_path: '/uas/oauth/accessToken'
    :authorize_path: '/uas/oauth/authorize'
    :api_host: 'https://api.linkedin.com'
  :linkedin_atoken: 9da0e8e3-611d-4c6a-9878-b37d084fd234
  :linkedin_asecret: add11471-12f2-48ce-9d1a-690400606391

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

